### ISSUE TITLE
view home page

### ISSUE THREAD

**Issue by abdhalees** [FACG2/Fac-Community#4]
- [x] styling(1d) https://github.com/FACG2/Fac-Community/issues/43

- [ ] get data from database(2h) https://github.com/FACG2/Fac-Community/issues/44

- [x] testing (1h) 
![21698204_489538548073583_306858880_n](https://user-images.githubusercontent.com/26231211/30536313-02847222-9c6e-11e7-9219-d760cf447519.jpg)

**Comment by aajour** [comment]
In our MVP, and because the lack of time, we will not add the `Activities`, so we don't need the task ` get data from database`
