### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by mahmoudalwadia** [FACG2/Fac-Community#9]
.
    ├─── public
    │             ├─── style
    │             └─── js
    ├─── src
    │         ├─── controllers
    │         ├─── model 
    │         │              ├─── database
    │         │              └─── queries
    │         ├─── tests
    │         ├─── views
    │         │             ├─── layouts
    │         │             └─── partials
    │         ├─── app.js
    │         └─── index.js
    │
    ├─── .gitignore                
    ├─── config.js                  
    ├─── pacjage.json           
    └─── README.md

**Comment by aajour** [comment]
Done.
